/**
 * Generated official-vendor and model presets for the SDKWork voice model
 * configuration page: the catalog's own speech synthesis and transcription vendors with their canonical
 * API roots, and every catalog model in that modality.
 *
 * Source: sdkwork-models catalog 2026.09.17.1 (generatedAt 2026-09-17T00:00:00Z).
 * Regenerate with `node scripts/generate-sdkwork-model-presets.mjs`; do not edit by hand.
 */

/** One official vendor root the voice settings page can seed. */
export interface SdkworkVoiceVendorPreset {
  /** sdkwork-models vendor code. */
  readonly vendor: string
  /** Vendor name as the catalog spells it. */
  readonly displayName: string
  /** Catalog region this root belongs to (`global`, `cn`). */
  readonly region: string
  /** Preferred protocol code; empty when the catalog publishes no compatible root. */
  readonly protocol: string
  /** Canonical API root; empty when the catalog publishes no compatible root. */
  readonly baseUrl: string
  /** Every protocol code the vendor publishes a root for. */
  readonly protocols: readonly string[]
}

/** One catalog model the voice settings page can offer. */
export interface SdkworkVoiceModelPreset {
  /** Catalog key (`<vendor>/<modelId>`). */
  readonly catalogKey: string
  /** Wire model id the provider expects. */
  readonly modelId: string
  /** Vendor name as the catalog spells it. */
  readonly displayName: string
  /** Owning sdkwork-models vendor code. */
  readonly vendor: string
  /** Catalog region this model belongs to. */
  readonly region: string
  /** Vendor API shape the catalog records for the model. */
  readonly apiFormat: string
  /** Catalog lifecycle stage. */
  readonly lifecycle: string
}

/** Official vendor roots with a voice capability. */
export const OFFICIAL_VOICE_VENDOR_PRESETS: readonly SdkworkVoiceVendorPreset[] = [
  {
    vendor: 'bytedance',
    displayName: 'ByteDance',
    region: 'cn',
    protocol: 'openai_compatible',
    baseUrl: 'https://ark.cn-beijing.volces.com/api/v3',
    protocols: ['openai_compatible', 'openai_responses'],
  },
  {
    vendor: 'elevenlabs',
    displayName: 'ElevenLabs',
    region: 'global',
    protocol: '',
    baseUrl: '',
    protocols: [],
  },
  {
    vendor: 'google',
    displayName: 'Google',
    region: 'global',
    protocol: 'openai_compatible',
    baseUrl: 'https://generativelanguage.googleapis.com/v1beta/openai',
    protocols: ['openai_compatible'],
  },
  {
    vendor: 'minimax',
    displayName: 'MiniMax',
    region: 'cn',
    protocol: 'openai_compatible',
    baseUrl: 'https://api.minimaxi.com/v1',
    protocols: ['openai_compatible'],
  },
  {
    vendor: 'minimax',
    displayName: 'MiniMax',
    region: 'global',
    protocol: 'openai_compatible',
    baseUrl: 'https://api.minimaxi.com/v1',
    protocols: ['openai_compatible'],
  },
  {
    vendor: 'openai',
    displayName: 'OpenAI',
    region: 'global',
    protocol: 'openai_compatible',
    baseUrl: 'https://api.openai.com/v1',
    protocols: ['openai_compatible', 'openai_responses'],
  },
  {
    vendor: 'xiaomi',
    displayName: 'Xiaomi MiMo',
    region: 'cn',
    protocol: 'openai_compatible',
    baseUrl: 'https://api.xiaomimimo.com/v1',
    protocols: ['anthropic_messages', 'openai_compatible'],
  },
  {
    vendor: 'xiaomi',
    displayName: 'Xiaomi MiMo',
    region: 'global',
    protocol: 'openai_compatible',
    baseUrl: 'https://api.xiaomimimo.com/v1',
    protocols: ['anthropic_messages', 'openai_compatible'],
  },
]

/** Every catalog model whose primary capability is voice. */
export const CATALOG_VOICE_MODEL_PRESETS: readonly SdkworkVoiceModelPreset[] = [
  {
    catalogKey: 'bytedance/seed-tts-2.0-expressive',
    modelId: 'seed-tts-2.0-expressive',
    displayName: 'Seed TTS 2.0 Expressive',
    vendor: 'bytedance',
    region: 'cn',
    apiFormat: 'vendor_native',
    lifecycle: 'active',
  },
  {
    catalogKey: 'bytedance/seed-tts-2.0-standard',
    modelId: 'seed-tts-2.0-standard',
    displayName: 'Seed TTS 2.0 Standard',
    vendor: 'bytedance',
    region: 'cn',
    apiFormat: 'vendor_native',
    lifecycle: 'active',
  },
  {
    catalogKey: 'elevenlabs/eleven_flash_v2',
    modelId: 'eleven_flash_v2',
    displayName: 'Eleven Flash v2',
    vendor: 'elevenlabs',
    region: 'global',
    apiFormat: 'vendor_native',
    lifecycle: 'active',
  },
  {
    catalogKey: 'elevenlabs/eleven_flash_v2_5',
    modelId: 'eleven_flash_v2_5',
    displayName: 'Eleven Flash v2.5',
    vendor: 'elevenlabs',
    region: 'global',
    apiFormat: 'vendor_native',
    lifecycle: 'active',
  },
  {
    catalogKey: 'elevenlabs/eleven_monolingual_v1',
    modelId: 'eleven_monolingual_v1',
    displayName: 'Eleven Monolingual V1',
    vendor: 'elevenlabs',
    region: 'global',
    apiFormat: 'vendor_native',
    lifecycle: 'deprecated',
  },
  {
    catalogKey: 'elevenlabs/eleven_multilingual_v1',
    modelId: 'eleven_multilingual_v1',
    displayName: 'Eleven Multilingual V1',
    vendor: 'elevenlabs',
    region: 'global',
    apiFormat: 'vendor_native',
    lifecycle: 'deprecated',
  },
  {
    catalogKey: 'elevenlabs/eleven_multilingual_v2',
    modelId: 'eleven_multilingual_v2',
    displayName: 'Eleven Multilingual v2',
    vendor: 'elevenlabs',
    region: 'global',
    apiFormat: 'vendor_native',
    lifecycle: 'active',
  },
  {
    catalogKey: 'elevenlabs/eleven_v3',
    modelId: 'eleven_v3',
    displayName: 'Eleven v3',
    vendor: 'elevenlabs',
    region: 'global',
    apiFormat: 'vendor_native',
    lifecycle: 'active',
  },
  {
    catalogKey: 'elevenlabs/eleven_v3_conversational',
    modelId: 'eleven_v3_conversational',
    displayName: 'Eleven v3 Conversational',
    vendor: 'elevenlabs',
    region: 'global',
    apiFormat: 'vendor_native',
    lifecycle: 'active',
  },
  {
    catalogKey: 'elevenlabs/scribe_v1',
    modelId: 'scribe_v1',
    displayName: 'Scribe v1',
    vendor: 'elevenlabs',
    region: 'global',
    apiFormat: 'vendor_native',
    lifecycle: 'deprecated',
  },
  {
    catalogKey: 'elevenlabs/scribe_v2',
    modelId: 'scribe_v2',
    displayName: 'Scribe v2',
    vendor: 'elevenlabs',
    region: 'global',
    apiFormat: 'vendor_native',
    lifecycle: 'active',
  },
  {
    catalogKey: 'elevenlabs/scribe_v2_medical',
    modelId: 'scribe_v2_medical',
    displayName: 'Scribe v2 Medical',
    vendor: 'elevenlabs',
    region: 'global',
    apiFormat: 'vendor_native',
    lifecycle: 'active',
  },
  {
    catalogKey: 'elevenlabs/scribe_v2_realtime',
    modelId: 'scribe_v2_realtime',
    displayName: 'Scribe v2 Realtime',
    vendor: 'elevenlabs',
    region: 'global',
    apiFormat: 'vendor_native',
    lifecycle: 'active',
  },
  {
    catalogKey: 'google/gemini-2.5-flash-preview-tts',
    modelId: 'gemini-2.5-flash-preview-tts',
    displayName: 'Gemini 2.5 Flash TTS Preview',
    vendor: 'google',
    region: 'global',
    apiFormat: 'google_gemini',
    lifecycle: 'preview',
  },
  {
    catalogKey: 'google/gemini-2.5-pro-preview-tts',
    modelId: 'gemini-2.5-pro-preview-tts',
    displayName: 'Gemini 2.5 Pro TTS Preview',
    vendor: 'google',
    region: 'global',
    apiFormat: 'google_gemini',
    lifecycle: 'preview',
  },
  {
    catalogKey: 'google/gemini-3.1-flash-tts-preview',
    modelId: 'gemini-3.1-flash-tts-preview',
    displayName: 'Gemini 3.1 Flash TTS Preview',
    vendor: 'google',
    region: 'global',
    apiFormat: 'google_gemini',
    lifecycle: 'preview',
  },
  {
    catalogKey: 'google/gemini-3.5-live-translate-preview',
    modelId: 'gemini-3.5-live-translate-preview',
    displayName: 'Gemini 3.5 Live Translate',
    vendor: 'google',
    region: 'global',
    apiFormat: 'google_gemini',
    lifecycle: 'preview',
  },
  {
    catalogKey: 'google/gemini-3.5-transcribe',
    modelId: 'gemini-3.5-transcribe',
    displayName: 'Gemini 3.5 Transcribe',
    vendor: 'google',
    region: 'global',
    apiFormat: 'google_gemini',
    lifecycle: 'active',
  },
  {
    catalogKey: 'google/gemini-3.5-transcribe-live',
    modelId: 'gemini-3.5-transcribe-live',
    displayName: 'Gemini 3.5 Transcribe Live',
    vendor: 'google',
    region: 'global',
    apiFormat: 'google_gemini',
    lifecycle: 'active',
  },
  {
    catalogKey: 'minimax/speech-02-hd',
    modelId: 'speech-02-hd',
    displayName: 'MiniMax Speech 02 HD',
    vendor: 'minimax',
    region: 'cn',
    apiFormat: 'vendor_native',
    lifecycle: 'active',
  },
  {
    catalogKey: 'minimax/speech-02-hd',
    modelId: 'speech-02-hd',
    displayName: 'MiniMax Speech 02 HD',
    vendor: 'minimax',
    region: 'global',
    apiFormat: 'vendor_native',
    lifecycle: 'active',
  },
  {
    catalogKey: 'minimax/speech-02-turbo',
    modelId: 'speech-02-turbo',
    displayName: 'MiniMax Speech 02 Turbo',
    vendor: 'minimax',
    region: 'cn',
    apiFormat: 'vendor_native',
    lifecycle: 'active',
  },
  {
    catalogKey: 'minimax/speech-02-turbo',
    modelId: 'speech-02-turbo',
    displayName: 'MiniMax Speech 02 Turbo',
    vendor: 'minimax',
    region: 'global',
    apiFormat: 'vendor_native',
    lifecycle: 'active',
  },
  {
    catalogKey: 'minimax/speech-2.6-hd',
    modelId: 'speech-2.6-hd',
    displayName: 'MiniMax Speech 2.6 HD',
    vendor: 'minimax',
    region: 'cn',
    apiFormat: 'vendor_native',
    lifecycle: 'active',
  },
  {
    catalogKey: 'minimax/speech-2.6-hd',
    modelId: 'speech-2.6-hd',
    displayName: 'MiniMax Speech 2.6 HD',
    vendor: 'minimax',
    region: 'global',
    apiFormat: 'vendor_native',
    lifecycle: 'active',
  },
  {
    catalogKey: 'minimax/speech-2.6-turbo',
    modelId: 'speech-2.6-turbo',
    displayName: 'MiniMax Speech 2.6 Turbo',
    vendor: 'minimax',
    region: 'cn',
    apiFormat: 'vendor_native',
    lifecycle: 'active',
  },
  {
    catalogKey: 'minimax/speech-2.6-turbo',
    modelId: 'speech-2.6-turbo',
    displayName: 'MiniMax Speech 2.6 Turbo',
    vendor: 'minimax',
    region: 'global',
    apiFormat: 'vendor_native',
    lifecycle: 'active',
  },
  {
    catalogKey: 'minimax/speech-2.8-hd',
    modelId: 'speech-2.8-hd',
    displayName: 'MiniMax Speech 2.8 HD',
    vendor: 'minimax',
    region: 'cn',
    apiFormat: 'vendor_native',
    lifecycle: 'active',
  },
  {
    catalogKey: 'minimax/speech-2.8-hd',
    modelId: 'speech-2.8-hd',
    displayName: 'MiniMax Speech 2.8 HD',
    vendor: 'minimax',
    region: 'global',
    apiFormat: 'vendor_native',
    lifecycle: 'active',
  },
  {
    catalogKey: 'minimax/speech-2.8-turbo',
    modelId: 'speech-2.8-turbo',
    displayName: 'MiniMax Speech 2.8 Turbo',
    vendor: 'minimax',
    region: 'cn',
    apiFormat: 'vendor_native',
    lifecycle: 'active',
  },
  {
    catalogKey: 'minimax/speech-2.8-turbo',
    modelId: 'speech-2.8-turbo',
    displayName: 'MiniMax Speech 2.8 Turbo',
    vendor: 'minimax',
    region: 'global',
    apiFormat: 'vendor_native',
    lifecycle: 'active',
  },
  {
    catalogKey: 'openai/gpt-4o-mini-transcribe',
    modelId: 'gpt-4o-mini-transcribe',
    displayName: 'GPT-4o mini Transcribe',
    vendor: 'openai',
    region: 'global',
    apiFormat: 'openai_compatible',
    lifecycle: 'deprecated',
  },
  {
    catalogKey: 'openai/gpt-4o-mini-tts',
    modelId: 'gpt-4o-mini-tts',
    displayName: 'GPT-4o mini TTS',
    vendor: 'openai',
    region: 'global',
    apiFormat: 'openai_compatible',
    lifecycle: 'active',
  },
  {
    catalogKey: 'openai/gpt-4o-transcribe',
    modelId: 'gpt-4o-transcribe',
    displayName: 'GPT-4o transcribe',
    vendor: 'openai',
    region: 'global',
    apiFormat: 'openai_compatible',
    lifecycle: 'deprecated',
  },
  {
    catalogKey: 'openai/gpt-4o-transcribe-diarize',
    modelId: 'gpt-4o-transcribe-diarize',
    displayName: 'GPT-4o transcribe diarize',
    vendor: 'openai',
    region: 'global',
    apiFormat: 'openai_compatible',
    lifecycle: 'deprecated',
  },
  {
    catalogKey: 'openai/gpt-audio-1.5',
    modelId: 'gpt-audio-1.5',
    displayName: 'GPT Audio 1.5',
    vendor: 'openai',
    region: 'global',
    apiFormat: 'openai_compatible',
    lifecycle: 'active',
  },
  {
    catalogKey: 'openai/gpt-live-1',
    modelId: 'gpt-live-1',
    displayName: 'GPT-Live 1',
    vendor: 'openai',
    region: 'global',
    apiFormat: 'openai_compatible',
    lifecycle: 'active',
  },
  {
    catalogKey: 'openai/gpt-live-transcribe',
    modelId: 'gpt-live-transcribe',
    displayName: 'GPT-Live Transcribe',
    vendor: 'openai',
    region: 'global',
    apiFormat: 'openai_compatible',
    lifecycle: 'active',
  },
  {
    catalogKey: 'openai/gpt-realtime-1.5',
    modelId: 'gpt-realtime-1.5',
    displayName: 'GPT Realtime 1.5',
    vendor: 'openai',
    region: 'global',
    apiFormat: 'openai_compatible',
    lifecycle: 'active',
  },
  {
    catalogKey: 'openai/gpt-realtime-2',
    modelId: 'gpt-realtime-2',
    displayName: 'GPT Realtime 2',
    vendor: 'openai',
    region: 'global',
    apiFormat: 'openai_compatible',
    lifecycle: 'active',
  },
  {
    catalogKey: 'openai/gpt-realtime-2.1',
    modelId: 'gpt-realtime-2.1',
    displayName: 'GPT Realtime 2.1',
    vendor: 'openai',
    region: 'global',
    apiFormat: 'openai_compatible',
    lifecycle: 'active',
  },
  {
    catalogKey: 'openai/gpt-realtime-2.1-mini',
    modelId: 'gpt-realtime-2.1-mini',
    displayName: 'GPT Realtime 2.1 Mini',
    vendor: 'openai',
    region: 'global',
    apiFormat: 'openai_compatible',
    lifecycle: 'active',
  },
  {
    catalogKey: 'openai/gpt-realtime-mini',
    modelId: 'gpt-realtime-mini',
    displayName: 'GPT-Realtime mini',
    vendor: 'openai',
    region: 'global',
    apiFormat: 'openai_compatible',
    lifecycle: 'deprecated',
  },
  {
    catalogKey: 'openai/gpt-realtime-translate',
    modelId: 'gpt-realtime-translate',
    displayName: 'GPT-Realtime-Translate',
    vendor: 'openai',
    region: 'global',
    apiFormat: 'openai_compatible',
    lifecycle: 'active',
  },
  {
    catalogKey: 'openai/gpt-realtime-whisper',
    modelId: 'gpt-realtime-whisper',
    displayName: 'GPT-Realtime-Whisper',
    vendor: 'openai',
    region: 'global',
    apiFormat: 'openai_compatible',
    lifecycle: 'active',
  },
  {
    catalogKey: 'openai/gpt-transcribe',
    modelId: 'gpt-transcribe',
    displayName: 'GPT Transcribe',
    vendor: 'openai',
    region: 'global',
    apiFormat: 'openai_compatible',
    lifecycle: 'active',
  },
  {
    catalogKey: 'openai/tts-1-hd',
    modelId: 'tts-1-hd',
    displayName: 'TTS-1 HD',
    vendor: 'openai',
    region: 'global',
    apiFormat: 'openai_compatible',
    lifecycle: 'active',
  },
  {
    catalogKey: 'openai/whisper-1',
    modelId: 'whisper-1',
    displayName: 'Whisper 1',
    vendor: 'openai',
    region: 'global',
    apiFormat: 'openai_compatible',
    lifecycle: 'deprecated',
  },
  {
    catalogKey: 'xiaomi/mimo-v2.5-asr',
    modelId: 'mimo-v2.5-asr',
    displayName: 'MiMo V2.5 ASR',
    vendor: 'xiaomi',
    region: 'cn',
    apiFormat: 'openai_compatible',
    lifecycle: 'active',
  },
  {
    catalogKey: 'xiaomi/mimo-v2.5-asr',
    modelId: 'mimo-v2.5-asr',
    displayName: 'MiMo V2.5 ASR',
    vendor: 'xiaomi',
    region: 'global',
    apiFormat: 'openai_compatible',
    lifecycle: 'active',
  },
  {
    catalogKey: 'xiaomi/mimo-v2.5-tts',
    modelId: 'mimo-v2.5-tts',
    displayName: 'MiMo V2.5 TTS',
    vendor: 'xiaomi',
    region: 'cn',
    apiFormat: 'openai_compatible',
    lifecycle: 'catalog_only',
  },
  {
    catalogKey: 'xiaomi/mimo-v2.5-tts',
    modelId: 'mimo-v2.5-tts',
    displayName: 'MiMo V2.5 TTS',
    vendor: 'xiaomi',
    region: 'global',
    apiFormat: 'openai_compatible',
    lifecycle: 'catalog_only',
  },
  {
    catalogKey: 'xiaomi/mimo-v2.5-tts-voiceclone',
    modelId: 'mimo-v2.5-tts-voiceclone',
    displayName: 'MiMo V2.5 TTS Voice Clone',
    vendor: 'xiaomi',
    region: 'cn',
    apiFormat: 'openai_compatible',
    lifecycle: 'catalog_only',
  },
  {
    catalogKey: 'xiaomi/mimo-v2.5-tts-voiceclone',
    modelId: 'mimo-v2.5-tts-voiceclone',
    displayName: 'MiMo V2.5 TTS Voice Clone',
    vendor: 'xiaomi',
    region: 'global',
    apiFormat: 'openai_compatible',
    lifecycle: 'catalog_only',
  },
  {
    catalogKey: 'xiaomi/mimo-v2.5-tts-voicedesign',
    modelId: 'mimo-v2.5-tts-voicedesign',
    displayName: 'MiMo V2.5 TTS Voice Design',
    vendor: 'xiaomi',
    region: 'cn',
    apiFormat: 'openai_compatible',
    lifecycle: 'catalog_only',
  },
  {
    catalogKey: 'xiaomi/mimo-v2.5-tts-voicedesign',
    modelId: 'mimo-v2.5-tts-voicedesign',
    displayName: 'MiMo V2.5 TTS Voice Design',
    vendor: 'xiaomi',
    region: 'global',
    apiFormat: 'openai_compatible',
    lifecycle: 'catalog_only',
  },
]
