{{- if not .Values.auth.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sdkwork-birdcoder2.fullname" . }}-auth
  labels:
    app.kubernetes.io/name: sdkwork-birdcoder2
type: Opaque
stringData:
  manageUsername: {{ required "A valid .Values.auth.manageUsername is required" .Values.auth.manageUsername }}
  managePassword: {{ required "A valid .Values.auth.managePassword is required" .Values.auth.managePassword }}
{{- end -}}
