{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "sdkwork-birdcoder2.fullname" . }}
  labels:
    app.kubernetes.io/name: sdkwork-birdcoder2
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: sdkwork-birdcoder2
  endpoints:
    - port: http
      path: {{ .Values.serviceMonitor.path }}
      interval: {{ .Values.serviceMonitor.interval }}
      scrapeTimeout: {{ .Values.serviceMonitor.scrapeTimeout }}
{{- end }}
