/** `generationsAssets` namespace dictionaries: the rail entry and asset library page. */

/** Simplified Chinese dictionary (the key-set source of truth). */
export const zh = {
  'mode.assets': '生成资产',
  'mode.assets.label': '生成资产模式',
  'page.title': '生成资产',
  'page.subtitle': '查看 SDKWork Agents 生成的媒体资产',
  'page.filter.all': '全部',
  'page.filter.image': '图片',
  'page.filter.video': '视频',
  'page.filter.audio': '音频',
  'page.filter.other': '其他',
  'page.configure': '请先在设置中配置 SDKWork API 环境。',
  'page.loading': '正在加载资产…',
  'page.empty': '暂时没有生成资产。',
  'page.error': '资产列表加载失败，请稍后重试。',
  'page.retry': '重新加载',
  'page.group.unknown': '未知日期',
  'page.detail': '资产详情',
  'page.detail.close': '关闭',
  'page.detail.tool': '生成工具',
  'page.detail.created': '创建时间',
  'page.detail.drive': 'Drive 位置',
  'page.item': '生成资产',
} satisfies Record<string, string>

/** The generationsAssets namespace key union. */
export type AssetsGenerationsKey = keyof typeof zh

/** English dictionary, checked complete against the zh key set. */
export const en = {
  'mode.assets': 'Generated assets',
  'mode.assets.label': 'Generated assets mode',
  'page.title': 'Generated assets',
  'page.subtitle': 'Browse media assets generated by SDKWork Agents',
  'page.filter.all': 'All',
  'page.filter.image': 'Images',
  'page.filter.video': 'Videos',
  'page.filter.audio': 'Audio',
  'page.filter.other': 'Other',
  'page.configure': 'Configure an SDKWork API environment in Settings first.',
  'page.loading': 'Loading assets…',
  'page.empty': 'There are no generated assets yet.',
  'page.error': 'The assets could not be loaded. Try again later.',
  'page.retry': 'Retry',
  'page.group.unknown': 'Unknown date',
  'page.detail': 'Asset details',
  'page.detail.close': 'Close',
  'page.detail.tool': 'Tool',
  'page.detail.created': 'Created',
  'page.detail.drive': 'Drive location',
  'page.item': 'Generated asset',
} satisfies Record<AssetsGenerationsKey, string>
