/**
 * Generated official-vendor and model presets for the SDKWork image model
 * configuration page: the catalog's own image generation and editing vendors with their canonical
 * API roots, and every catalog model in that modality.
 *
 * Source: sdkwork-models catalog 2026.09.17.1 (generatedAt 2026-09-17T00:00:00Z).
 * Regenerate with `node scripts/generate-sdkwork-model-presets.mjs`; do not edit by hand.
 */

/** One official vendor root the image settings page can seed. */
export interface SdkworkImageVendorPreset {
  /** sdkwork-models vendor code. */
  readonly vendor: string
  /** Vendor name as the catalog spells it. */
  readonly displayName: string
  /** Catalog region this root belongs to (`global`, `cn`). */
  readonly region: string
  /** Preferred protocol code; empty when the catalog publishes no compatible root. */
  readonly protocol: string
  /** Canonical API root; empty when the catalog publishes no compatible root. */
  readonly baseUrl: string
  /** Every protocol code the vendor publishes a root for. */
  readonly protocols: readonly string[]
}

/** One catalog model the image settings page can offer. */
export interface SdkworkImageModelPreset {
  /** Catalog key (`<vendor>/<modelId>`). */
  readonly catalogKey: string
  /** Wire model id the provider expects. */
  readonly modelId: string
  /** Vendor name as the catalog spells it. */
  readonly displayName: string
  /** Owning sdkwork-models vendor code. */
  readonly vendor: string
  /** Catalog region this model belongs to. */
  readonly region: string
  /** Vendor API shape the catalog records for the model. */
  readonly apiFormat: string
  /** Catalog lifecycle stage. */
  readonly lifecycle: string
}

/** Official vendor roots with a image capability. */
export const OFFICIAL_IMAGE_VENDOR_PRESETS: readonly SdkworkImageVendorPreset[] = [
  {
    vendor: 'alibaba',
    displayName: 'Alibaba Cloud',
    region: 'cn',
    protocol: 'openai_compatible',
    baseUrl: 'https://dashscope.aliyuncs.com/compatible-mode/v1',
    protocols: ['anthropic_messages', 'openai_compatible', 'openai_responses'],
  },
  {
    vendor: 'black_forest_labs',
    displayName: 'Black Forest Labs',
    region: 'global',
    protocol: '',
    baseUrl: '',
    protocols: [],
  },
  {
    vendor: 'bytedance',
    displayName: 'ByteDance',
    region: 'cn',
    protocol: 'openai_compatible',
    baseUrl: 'https://ark.cn-beijing.volces.com/api/v3',
    protocols: ['openai_compatible', 'openai_responses'],
  },
  {
    vendor: 'google',
    displayName: 'Google',
    region: 'global',
    protocol: 'openai_compatible',
    baseUrl: 'https://generativelanguage.googleapis.com/v1beta/openai',
    protocols: ['openai_compatible'],
  },
  {
    vendor: 'kuaishou',
    displayName: 'Kuaishou',
    region: 'cn',
    protocol: '',
    baseUrl: '',
    protocols: [],
  },
  {
    vendor: 'kuaishou',
    displayName: 'Kuaishou',
    region: 'global',
    protocol: '',
    baseUrl: '',
    protocols: [],
  },
  {
    vendor: 'minimax',
    displayName: 'MiniMax',
    region: 'cn',
    protocol: 'openai_compatible',
    baseUrl: 'https://api.minimaxi.com/v1',
    protocols: ['openai_compatible'],
  },
  {
    vendor: 'minimax',
    displayName: 'MiniMax',
    region: 'global',
    protocol: 'openai_compatible',
    baseUrl: 'https://api.minimaxi.com/v1',
    protocols: ['openai_compatible'],
  },
  {
    vendor: 'openai',
    displayName: 'OpenAI',
    region: 'global',
    protocol: 'openai_compatible',
    baseUrl: 'https://api.openai.com/v1',
    protocols: ['openai_compatible', 'openai_responses'],
  },
  {
    vendor: 'runway',
    displayName: 'Runway',
    region: 'global',
    protocol: '',
    baseUrl: '',
    protocols: [],
  },
  {
    vendor: 'stability_ai',
    displayName: 'Stability AI',
    region: 'global',
    protocol: '',
    baseUrl: '',
    protocols: [],
  },
  {
    vendor: 'vidu',
    displayName: 'Vidu',
    region: 'global',
    protocol: '',
    baseUrl: '',
    protocols: [],
  },
  {
    vendor: 'xai',
    displayName: 'xAI',
    region: 'global',
    protocol: 'openai_compatible',
    baseUrl: 'https://api.x.ai/v1',
    protocols: ['openai_compatible', 'openai_responses'],
  },
  {
    vendor: 'zhipu',
    displayName: 'Zhipu AI',
    region: 'cn',
    protocol: 'openai_compatible',
    baseUrl: 'https://open.bigmodel.cn/api/paas/v4',
    protocols: ['anthropic_messages', 'openai_compatible'],
  },
]

/** Every catalog model whose primary capability is image. */
export const CATALOG_IMAGE_MODEL_PRESETS: readonly SdkworkImageModelPreset[] = [
  {
    catalogKey: 'alibaba/wan2.6-t2i',
    modelId: 'wan2.6-t2i',
    displayName: 'Wan 2.6 Text to Image',
    vendor: 'alibaba',
    region: 'cn',
    apiFormat: 'openai_compatible',
    lifecycle: 'active',
  },
  {
    catalogKey: 'black_forest_labs/flux-2-dev',
    modelId: 'flux-2-dev',
    displayName: 'FLUX.2 [dev]',
    vendor: 'black_forest_labs',
    region: 'global',
    apiFormat: 'vendor_native',
    lifecycle: 'catalog_only',
  },
  {
    catalogKey: 'black_forest_labs/flux-2-flex',
    modelId: 'flux-2-flex',
    displayName: 'FLUX.2 Flex',
    vendor: 'black_forest_labs',
    region: 'global',
    apiFormat: 'vendor_native',
    lifecycle: 'active',
  },
  {
    catalogKey: 'black_forest_labs/flux-2-klein-4b',
    modelId: 'flux-2-klein-4b',
    displayName: 'FLUX.2 Klein 4B',
    vendor: 'black_forest_labs',
    region: 'global',
    apiFormat: 'vendor_native',
    lifecycle: 'active',
  },
  {
    catalogKey: 'black_forest_labs/flux-2-klein-9b',
    modelId: 'flux-2-klein-9b',
    displayName: 'FLUX.2 Klein 9B',
    vendor: 'black_forest_labs',
    region: 'global',
    apiFormat: 'vendor_native',
    lifecycle: 'active',
  },
  {
    catalogKey: 'black_forest_labs/flux-2-max',
    modelId: 'flux-2-max',
    displayName: 'FLUX.2 Max',
    vendor: 'black_forest_labs',
    region: 'global',
    apiFormat: 'vendor_native',
    lifecycle: 'active',
  },
  {
    catalogKey: 'black_forest_labs/flux-2-pro',
    modelId: 'flux-2-pro',
    displayName: 'FLUX.2 Pro',
    vendor: 'black_forest_labs',
    region: 'global',
    apiFormat: 'vendor_native',
    lifecycle: 'active',
  },
  {
    catalogKey: 'black_forest_labs/flux-kontext-max',
    modelId: 'flux-kontext-max',
    displayName: 'FLUX.1 Kontext [max]',
    vendor: 'black_forest_labs',
    region: 'global',
    apiFormat: 'vendor_native',
    lifecycle: 'active',
  },
  {
    catalogKey: 'black_forest_labs/flux-kontext-pro',
    modelId: 'flux-kontext-pro',
    displayName: 'FLUX.1 Kontext [pro]',
    vendor: 'black_forest_labs',
    region: 'global',
    apiFormat: 'vendor_native',
    lifecycle: 'active',
  },
  {
    catalogKey: 'black_forest_labs/flux-pro-1.0-fill',
    modelId: 'flux-pro-1.0-fill',
    displayName: 'FLUX.1 Fill [pro]',
    vendor: 'black_forest_labs',
    region: 'global',
    apiFormat: 'vendor_native',
    lifecycle: 'active',
  },
  {
    catalogKey: 'black_forest_labs/flux-pro-1.1',
    modelId: 'flux-pro-1.1',
    displayName: 'FLUX1.1 [pro]',
    vendor: 'black_forest_labs',
    region: 'global',
    apiFormat: 'vendor_native',
    lifecycle: 'active',
  },
  {
    catalogKey: 'black_forest_labs/flux-pro-1.1-raw',
    modelId: 'flux-pro-1.1-raw',
    displayName: 'FLUX1.1 [pro] Raw',
    vendor: 'black_forest_labs',
    region: 'global',
    apiFormat: 'vendor_native',
    lifecycle: 'active',
  },
  {
    catalogKey: 'black_forest_labs/flux-pro-1.1-ultra',
    modelId: 'flux-pro-1.1-ultra',
    displayName: 'FLUX1.1 [pro] Ultra',
    vendor: 'black_forest_labs',
    region: 'global',
    apiFormat: 'vendor_native',
    lifecycle: 'active',
  },
  {
    catalogKey: 'bytedance/doubao-seedream-4-0-250828',
    modelId: 'doubao-seedream-4-0-250828',
    displayName: 'Seedream 4.0',
    vendor: 'bytedance',
    region: 'cn',
    apiFormat: 'openai_compatible',
    lifecycle: 'active',
  },
  {
    catalogKey: 'bytedance/doubao-seedream-4-5-251128',
    modelId: 'doubao-seedream-4-5-251128',
    displayName: 'Doubao Seedream 4.5',
    vendor: 'bytedance',
    region: 'cn',
    apiFormat: 'openai_compatible',
    lifecycle: 'active',
  },
  {
    catalogKey: 'bytedance/doubao-seedream-5-0-lite-260128',
    modelId: 'doubao-seedream-5-0-lite-260128',
    displayName: 'Doubao Seedream 5.0 Lite',
    vendor: 'bytedance',
    region: 'cn',
    apiFormat: 'openai_compatible',
    lifecycle: 'active',
  },
  {
    catalogKey: 'bytedance/doubao-seedream-5-0-pro-260628',
    modelId: 'doubao-seedream-5-0-pro-260628',
    displayName: 'Doubao Seedream 5.0 Pro',
    vendor: 'bytedance',
    region: 'cn',
    apiFormat: 'openai_compatible',
    lifecycle: 'active',
  },
  {
    catalogKey: 'google/gemini-2.5-flash-image',
    modelId: 'gemini-2.5-flash-image',
    displayName: 'Gemini 2.5 Flash Image',
    vendor: 'google',
    region: 'global',
    apiFormat: 'google_gemini',
    lifecycle: 'deprecated',
  },
  {
    catalogKey: 'google/gemini-3-pro-image',
    modelId: 'gemini-3-pro-image',
    displayName: 'Gemini 3 Pro Image',
    vendor: 'google',
    region: 'global',
    apiFormat: 'google_gemini',
    lifecycle: 'active',
  },
  {
    catalogKey: 'google/gemini-3.1-flash-image',
    modelId: 'gemini-3.1-flash-image',
    displayName: 'Gemini 3.1 Flash Image',
    vendor: 'google',
    region: 'global',
    apiFormat: 'google_gemini',
    lifecycle: 'active',
  },
  {
    catalogKey: 'google/gemini-3.1-flash-image-preview',
    modelId: 'gemini-3.1-flash-image-preview',
    displayName: 'Gemini 3.1 Flash Image Preview',
    vendor: 'google',
    region: 'global',
    apiFormat: 'google_gemini',
    lifecycle: 'retired',
  },
  {
    catalogKey: 'google/gemini-3.1-flash-lite-image',
    modelId: 'gemini-3.1-flash-lite-image',
    displayName: 'Gemini 3.1 Flash Lite Image (Nano Banana 2 Lite)',
    vendor: 'google',
    region: 'global',
    apiFormat: 'google_gemini',
    lifecycle: 'active',
  },
  {
    catalogKey: 'google/imagen-4.0-fast-generate-001',
    modelId: 'imagen-4.0-fast-generate-001',
    displayName: 'Imagen 4.0 Fast',
    vendor: 'google',
    region: 'global',
    apiFormat: 'vendor_native',
    lifecycle: 'retired',
  },
  {
    catalogKey: 'google/imagen-4.0-generate-001',
    modelId: 'imagen-4.0-generate-001',
    displayName: 'Imagen 4.0 Generate',
    vendor: 'google',
    region: 'global',
    apiFormat: 'vendor_native',
    lifecycle: 'retired',
  },
  {
    catalogKey: 'google/imagen-4.0-ultra-generate-001',
    modelId: 'imagen-4.0-ultra-generate-001',
    displayName: 'Imagen 4.0 Ultra',
    vendor: 'google',
    region: 'global',
    apiFormat: 'vendor_native',
    lifecycle: 'retired',
  },
  {
    catalogKey: 'kuaishou/kling-image-3.0',
    modelId: 'kling-image-3.0',
    displayName: 'Kling Image 3.0',
    vendor: 'kuaishou',
    region: 'cn',
    apiFormat: 'vendor_native',
    lifecycle: 'active',
  },
  {
    catalogKey: 'kuaishou/kling-image-3.0-omni',
    modelId: 'kling-image-3.0-omni',
    displayName: 'Kling Image 3.0 Omni',
    vendor: 'kuaishou',
    region: 'cn',
    apiFormat: 'vendor_native',
    lifecycle: 'active',
  },
  {
    catalogKey: 'kuaishou/kling-image-o1',
    modelId: 'kling-image-o1',
    displayName: 'Kling Image O1',
    vendor: 'kuaishou',
    region: 'cn',
    apiFormat: 'vendor_native',
    lifecycle: 'active',
  },
  {
    catalogKey: 'kuaishou/kling-image-o1',
    modelId: 'kling-image-o1',
    displayName: 'Kling Image O1',
    vendor: 'kuaishou',
    region: 'global',
    apiFormat: 'vendor_native',
    lifecycle: 'active',
  },
  {
    catalogKey: 'kuaishou/kling-v2-1',
    modelId: 'kling-v2-1',
    displayName: 'Kling Image 2.1',
    vendor: 'kuaishou',
    region: 'cn',
    apiFormat: 'vendor_native',
    lifecycle: 'active',
  },
  {
    catalogKey: 'kuaishou/kling-v2-1',
    modelId: 'kling-v2-1',
    displayName: 'Kling Image 2.1',
    vendor: 'kuaishou',
    region: 'global',
    apiFormat: 'vendor_native',
    lifecycle: 'active',
  },
  {
    catalogKey: 'minimax/image-01',
    modelId: 'image-01',
    displayName: 'MiniMax Image 01',
    vendor: 'minimax',
    region: 'cn',
    apiFormat: 'openai_compatible',
    lifecycle: 'active',
  },
  {
    catalogKey: 'minimax/image-01',
    modelId: 'image-01',
    displayName: 'MiniMax Image 01',
    vendor: 'minimax',
    region: 'global',
    apiFormat: 'openai_compatible',
    lifecycle: 'active',
  },
  {
    catalogKey: 'minimax/image-01-live',
    modelId: 'image-01-live',
    displayName: 'MiniMax Image 01 Live',
    vendor: 'minimax',
    region: 'cn',
    apiFormat: 'openai_compatible',
    lifecycle: 'active',
  },
  {
    catalogKey: 'openai/gpt-image-1.5',
    modelId: 'gpt-image-1.5',
    displayName: 'GPT Image 1.5',
    vendor: 'openai',
    region: 'global',
    apiFormat: 'openai_compatible',
    lifecycle: 'deprecated',
  },
  {
    catalogKey: 'openai/gpt-image-2',
    modelId: 'gpt-image-2',
    displayName: 'GPT Image 2',
    vendor: 'openai',
    region: 'global',
    apiFormat: 'openai_compatible',
    lifecycle: 'active',
  },
  {
    catalogKey: 'openai/gpt-image-2.5-flare',
    modelId: 'gpt-image-2.5-flare',
    displayName: 'GPT Image 2.5 Flare',
    vendor: 'openai',
    region: 'global',
    apiFormat: 'openai_compatible',
    lifecycle: 'active',
  },
  {
    catalogKey: 'openai/gpt-image-2.5-sunburst',
    modelId: 'gpt-image-2.5-sunburst',
    displayName: 'GPT Image 2.5 Sunburst',
    vendor: 'openai',
    region: 'global',
    apiFormat: 'openai_compatible',
    lifecycle: 'active',
  },
  {
    catalogKey: 'runway/gemini_2.5_flash',
    modelId: 'gemini_2.5_flash',
    displayName: 'Gemini 2.5 Flash Image',
    vendor: 'runway',
    region: 'global',
    apiFormat: 'vendor_native',
    lifecycle: 'active',
  },
  {
    catalogKey: 'runway/gemini_image3_pro',
    modelId: 'gemini_image3_pro',
    displayName: 'Gemini Image 3 Pro',
    vendor: 'runway',
    region: 'global',
    apiFormat: 'vendor_native',
    lifecycle: 'active',
  },
  {
    catalogKey: 'runway/gemini_image3.1_flash',
    modelId: 'gemini_image3.1_flash',
    displayName: 'Gemini Image 3.1 Flash',
    vendor: 'runway',
    region: 'global',
    apiFormat: 'vendor_native',
    lifecycle: 'preview',
  },
  {
    catalogKey: 'runway/gen4_image',
    modelId: 'gen4_image',
    displayName: 'Gen-4 Image',
    vendor: 'runway',
    region: 'global',
    apiFormat: 'vendor_native',
    lifecycle: 'active',
  },
  {
    catalogKey: 'runway/gen4_image_turbo',
    modelId: 'gen4_image_turbo',
    displayName: 'Gen-4 Image Turbo',
    vendor: 'runway',
    region: 'global',
    apiFormat: 'vendor_native',
    lifecycle: 'active',
  },
  {
    catalogKey: 'runway/gpt_image_2',
    modelId: 'gpt_image_2',
    displayName: 'GPT Image 2',
    vendor: 'runway',
    region: 'global',
    apiFormat: 'vendor_native',
    lifecycle: 'active',
  },
  {
    catalogKey: 'runway/gpt_image_2_5_flare',
    modelId: 'gpt_image_2_5_flare',
    displayName: 'GPT Image 2.5 Flare',
    vendor: 'runway',
    region: 'global',
    apiFormat: 'vendor_native',
    lifecycle: 'active',
  },
  {
    catalogKey: 'runway/gpt_image_2_5_sunburst',
    modelId: 'gpt_image_2_5_sunburst',
    displayName: 'GPT Image 2.5 Sunburst',
    vendor: 'runway',
    region: 'global',
    apiFormat: 'vendor_native',
    lifecycle: 'active',
  },
  {
    catalogKey: 'runway/grok_imagine_image_2',
    modelId: 'grok_imagine_image_2',
    displayName: 'Grok Imagine Image 2',
    vendor: 'runway',
    region: 'global',
    apiFormat: 'vendor_native',
    lifecycle: 'active',
  },
  {
    catalogKey: 'runway/magnific_precision_upscaler_v2',
    modelId: 'magnific_precision_upscaler_v2',
    displayName: 'Magnific Precision Upscaler V2',
    vendor: 'runway',
    region: 'global',
    apiFormat: 'vendor_native',
    lifecycle: 'active',
  },
  {
    catalogKey: 'runway/muse_image',
    modelId: 'muse_image',
    displayName: 'Muse Image',
    vendor: 'runway',
    region: 'global',
    apiFormat: 'vendor_native',
    lifecycle: 'active',
  },
  {
    catalogKey: 'runway/seedream5_lite',
    modelId: 'seedream5_lite',
    displayName: 'Seedream 5 Lite',
    vendor: 'runway',
    region: 'global',
    apiFormat: 'vendor_native',
    lifecycle: 'active',
  },
  {
    catalogKey: 'runway/seedream5_pro',
    modelId: 'seedream5_pro',
    displayName: 'Seedream 5 Pro',
    vendor: 'runway',
    region: 'global',
    apiFormat: 'vendor_native',
    lifecycle: 'active',
  },
  {
    catalogKey: 'stability_ai/sdxl-1-0',
    modelId: 'sdxl-1-0',
    displayName: 'SDXL 1.0',
    vendor: 'stability_ai',
    region: 'global',
    apiFormat: 'vendor_native',
    lifecycle: 'catalog_only',
  },
  {
    catalogKey: 'stability_ai/stable-diffusion-3-5-flash',
    modelId: 'stable-diffusion-3-5-flash',
    displayName: 'Stable Diffusion 3.5 Flash',
    vendor: 'stability_ai',
    region: 'global',
    apiFormat: 'vendor_native',
    lifecycle: 'active',
  },
  {
    catalogKey: 'stability_ai/stable-diffusion-3-5-large',
    modelId: 'stable-diffusion-3-5-large',
    displayName: 'Stable Diffusion 3.5 Large',
    vendor: 'stability_ai',
    region: 'global',
    apiFormat: 'vendor_native',
    lifecycle: 'active',
  },
  {
    catalogKey: 'stability_ai/stable-diffusion-3-5-large-turbo',
    modelId: 'stable-diffusion-3-5-large-turbo',
    displayName: 'Stable Diffusion 3.5 Large Turbo',
    vendor: 'stability_ai',
    region: 'global',
    apiFormat: 'vendor_native',
    lifecycle: 'active',
  },
  {
    catalogKey: 'stability_ai/stable-diffusion-3-5-medium',
    modelId: 'stable-diffusion-3-5-medium',
    displayName: 'Stable Diffusion 3.5 Medium',
    vendor: 'stability_ai',
    region: 'global',
    apiFormat: 'vendor_native',
    lifecycle: 'active',
  },
  {
    catalogKey: 'stability_ai/stable-image-core',
    modelId: 'stable-image-core',
    displayName: 'Stable Image Core',
    vendor: 'stability_ai',
    region: 'global',
    apiFormat: 'vendor_native',
    lifecycle: 'active',
  },
  {
    catalogKey: 'stability_ai/stable-image-ultra',
    modelId: 'stable-image-ultra',
    displayName: 'Stable Image Ultra',
    vendor: 'stability_ai',
    region: 'global',
    apiFormat: 'vendor_native',
    lifecycle: 'active',
  },
  {
    catalogKey: 'vidu/viduq1',
    modelId: 'viduq1',
    displayName: 'Vidu Q1 Image',
    vendor: 'vidu',
    region: 'global',
    apiFormat: 'vendor_native',
    lifecycle: 'active',
  },
  {
    catalogKey: 'vidu/viduq2',
    modelId: 'viduq2',
    displayName: 'Vidu Q2 Image',
    vendor: 'vidu',
    region: 'global',
    apiFormat: 'vendor_native',
    lifecycle: 'active',
  },
  {
    catalogKey: 'xai/grok-imagine-image',
    modelId: 'grok-imagine-image',
    displayName: 'Grok Imagine Image',
    vendor: 'xai',
    region: 'global',
    apiFormat: 'openai_compatible',
    lifecycle: 'active',
  },
  {
    catalogKey: 'xai/grok-imagine-image-2.0',
    modelId: 'grok-imagine-image-2.0',
    displayName: 'Grok Imagine Image 2.0',
    vendor: 'xai',
    region: 'global',
    apiFormat: 'openai_compatible',
    lifecycle: 'active',
  },
  {
    catalogKey: 'xai/grok-imagine-image-quality',
    modelId: 'grok-imagine-image-quality',
    displayName: 'Grok Imagine Image Quality',
    vendor: 'xai',
    region: 'global',
    apiFormat: 'openai_compatible',
    lifecycle: 'active',
  },
  {
    catalogKey: 'zhipu/cogview-4-250304',
    modelId: 'cogview-4-250304',
    displayName: 'CogView 4',
    vendor: 'zhipu',
    region: 'cn',
    apiFormat: 'openai_compatible',
    lifecycle: 'active',
  },
  {
    catalogKey: 'zhipu/glm-image',
    modelId: 'glm-image',
    displayName: 'GLM-Image',
    vendor: 'zhipu',
    region: 'cn',
    apiFormat: 'openai_compatible',
    lifecycle: 'active',
  },
]
