/**
 * Image format identification.
 *
 * A file's extension is a claim, and for images it is frequently wrong: a JPEG
 * saved from a camera may arrive as `.jfif`, a TIFF generated by a scanner as
 * `.tif`, and a renamed `.png` may be a JPEG. The preview therefore identifies
 * the format from its leading bytes and uses the extension only as a hint, so a
 * mislabelled file renders correctly and an undecodable one is explained by the
 * format it actually is.
 */

import type { SdkworkImagePreviewKey } from '../locales.ts'

/** How this preview can treat a format. */
export type ImageDelivery =
  /** The browser decodes it directly, including animation. */
  | 'native'
  /** This package decodes it into pixels itself. */
  | 'decoded'
  /** Gzip-wrapped, so the body inflates it before the browser decodes it. */
  | 'gzip'
  /** Known, but not decodable here; the reader gets an explanation. */
  | 'unsupported'

/** One identified image format. */
export interface ImageFormat {
  /** Short display name, as a reader would say it. */
  readonly name: string
  /** Media type used for the Blob URL, or the empty string when undecodable. */
  readonly mime: string
  readonly delivery: ImageDelivery
  /** Whether the format can carry multiple frames. */
  readonly animatable: boolean
  /**
   * Dictionary key of the sentence shown in place of an undrawable image.
   *
   * A key rather than the sentence: this module identifies bytes, and every
   * word the reader is shown belongs to the locale namespace, which is what
   * keeps an English reader from meeting a Chinese explanation.
   */
  readonly reasonKey?: SdkworkImagePreviewKey
}

/** Formats the browser decodes natively, including their container aliases. */
const NATIVE: Readonly<Record<string, ImageFormat | undefined>> = {
  png: { name: 'PNG', mime: 'image/png', delivery: 'native', animatable: true },
  jpeg: { name: 'JPEG', mime: 'image/jpeg', delivery: 'native', animatable: false },
  gif: { name: 'GIF', mime: 'image/gif', delivery: 'native', animatable: true },
  webp: { name: 'WebP', mime: 'image/webp', delivery: 'native', animatable: true },
  avif: { name: 'AVIF', mime: 'image/avif', delivery: 'native', animatable: true },
  bmp: { name: 'BMP', mime: 'image/bmp', delivery: 'native', animatable: false },
  ico: { name: 'ICO', mime: 'image/x-icon', delivery: 'native', animatable: false },
  svg: { name: 'SVG', mime: 'image/svg+xml', delivery: 'native', animatable: false },
}

/** Formats this package decodes into pixels. */
const DECODED: Readonly<Record<string, ImageFormat | undefined>> = {
  tiff: { name: 'TIFF', mime: 'image/tiff', delivery: 'decoded', animatable: false },
}

/** Formats that arrive gzipped and are inflated before the browser sees them. */
const COMPRESSED: Readonly<Record<string, ImageFormat | undefined>> = {
  svgz: { name: 'SVG', mime: 'image/svg+xml', delivery: 'gzip', animatable: false },
}

/**
 * Formats a reader may open that this preview recognizes but cannot draw.
 *
 * Every entry names a dictionary key rather than a sentence, so the body can
 * state the conversion the reader needs in the reader's own language.
 */
const UNSUPPORTED: Readonly<Record<string, ImageFormat | undefined>> = {
  heif: {
    name: 'HEIF',
    mime: '',
    delivery: 'unsupported',
    animatable: false,
    reasonKey: 'reason.heif',
  },
  jp2: {
    name: 'JPEG 2000',
    mime: '',
    delivery: 'unsupported',
    animatable: false,
    reasonKey: 'reason.jp2',
  },
  jxl: {
    name: 'JPEG XL',
    mime: '',
    delivery: 'unsupported',
    animatable: false,
    reasonKey: 'reason.jxl',
  },
  psd: {
    name: 'Photoshop',
    mime: '',
    delivery: 'unsupported',
    animatable: false,
    reasonKey: 'reason.psd',
  },
  raw: {
    name: 'RAW',
    mime: '',
    delivery: 'unsupported',
    animatable: false,
    reasonKey: 'reason.raw',
  },
  exr: {
    name: 'OpenEXR',
    mime: '',
    delivery: 'unsupported',
    animatable: false,
    reasonKey: 'reason.exr',
  },
  hdr: {
    name: 'Radiance HDR',
    mime: '',
    delivery: 'unsupported',
    animatable: false,
    reasonKey: 'reason.hdr',
  },
  dds: {
    name: 'DDS',
    mime: '',
    delivery: 'unsupported',
    animatable: false,
    reasonKey: 'reason.dds',
  },
  tga: {
    name: 'Targa',
    mime: '',
    delivery: 'unsupported',
    animatable: false,
    reasonKey: 'reason.tga',
  },
  eps: {
    name: 'EPS',
    mime: '',
    delivery: 'unsupported',
    animatable: false,
    reasonKey: 'reason.eps',
  },
  pnm: {
    name: 'Netpbm',
    mime: '',
    delivery: 'unsupported',
    animatable: false,
    reasonKey: 'reason.pnm',
  },
  qoi: {
    name: 'QOI',
    mime: '',
    delivery: 'unsupported',
    animatable: false,
    reasonKey: 'reason.qoi',
  },
  xpm: {
    name: 'XPM/XBM',
    mime: '',
    delivery: 'unsupported',
    animatable: false,
    reasonKey: 'reason.xpm',
  },
  icns: {
    name: 'ICNS',
    mime: '',
    delivery: 'unsupported',
    animatable: false,
    reasonKey: 'reason.icns',
  },
}

/** Format key each recognized suffix maps to. */
const EXTENSION_FORMATS: Readonly<Record<string, string>> = {
  png: 'png', apng: 'png',
  jpg: 'jpeg', jpeg: 'jpeg', jpe: 'jpeg', jfif: 'jpeg', jfi: 'jpeg',
  gif: 'gif',
  webp: 'webp',
  avif: 'avif', avifs: 'avif',
  bmp: 'bmp', dib: 'bmp',
  ico: 'ico', cur: 'ico', icns: 'icns',
  svg: 'svg', svgz: 'svgz',
  tif: 'tiff', tiff: 'tiff',
  heic: 'heif', heif: 'heif', hif: 'heif',
  jp2: 'jp2', j2k: 'jp2', jpf: 'jp2', jpx: 'jp2',
  jxl: 'jxl',
  psd: 'psd', psb: 'psd',
  cr2: 'raw', cr3: 'raw', nef: 'raw', arw: 'raw', dng: 'raw', orf: 'raw', rw2: 'raw', raf: 'raw', pef: 'raw',
  exr: 'exr',
  hdr: 'hdr', rgbe: 'hdr',
  dds: 'dds',
  tga: 'tga', icb: 'tga', vda: 'tga', vst: 'tga',
  eps: 'eps', epsf: 'eps', ai: 'eps',
  pbm: 'pnm', pgm: 'pnm', ppm: 'pnm', pnm: 'pnm', pam: 'pnm',
  qoi: 'qoi',
  xpm: 'xpm', xbm: 'xpm',
}

/**
 * Every suffix this preview claims.
 *
 * The set is deliberately wider than the builtin image reader's, so the formats
 * it knows how to explain arrive here rather than falling through to the
 * plain-text reader, which would report them as text.
 */
export const IMAGE_EXTENSIONS: readonly string[] = Object.keys(EXTENSION_FORMATS)

/**
 * Pick a named entry out of one of the format tables.
 *
 * The tables admit a missing key even though every key they declare is present,
 * so a lookup is a plain indexed read whose result the caller must narrow.
 * @param table - one of the format tables.
 * @param key - the entry's name.
 * @returns the format, or undefined when the table has no such entry.
 */
function pick(table: Readonly<Record<string, ImageFormat | undefined>>, key: string): ImageFormat | undefined {
  return table[key]
}

/** Look up a format by its table key. */
function formatByKey(key: string | undefined): ImageFormat | undefined {
  if (key === undefined) return undefined
  return pick(NATIVE, key) ?? pick(COMPRESSED, key) ?? pick(DECODED, key) ?? pick(UNSUPPORTED, key)
}

/**
 * The format a suffix names, when this preview recognizes the suffix.
 * @param extension - the suffix, without its dot, in any case.
 * @returns the format, or undefined for an unrecognized suffix.
 */
export function formatForExtension(extension: string): ImageFormat | undefined {
  return formatByKey(EXTENSION_FORMATS[extension.toLowerCase()])
}

/** Whether the bytes at an offset equal the given ASCII text. */
function matchesAscii(bytes: Uint8Array, offset: number, text: string): boolean {
  if (bytes.byteLength < offset + text.length) return false
  for (let index = 0; index < text.length; index += 1) {
    if (bytes[offset + index] !== text.charCodeAt(index)) return false
  }
  return true
}

/** The ISO base media file format brands the image formats are written under. */
const ISO_BRANDS: Readonly<Record<string, string | undefined>> = {
  avif: 'avif', avis: 'avif',
  heic: 'heif', heix: 'heif', hevc: 'heif', hevx: 'heif', heim: 'heif', heis: 'heif', mif1: 'heif', msf1: 'heif',
  jxl: 'jxl',
  jp2: 'jp2',
}

/** TIFF-based suffixes, which are containers rather than plain TIFF. */
const TIFF_BASED_RAW: Readonly<Record<string, string | undefined>> = { CR: 'raw', RW2: 'raw' }

/**
 * Identify an image from its leading bytes.
 *
 * This is the authoritative answer; the extension is only a hint. A recognizable
 * signature always wins, and a file whose signature this preview does not know
 * falls back to what its suffix claimed, so an unfamiliar-but-named format is
 * still explained rather than reported as an unknown file.
 * @param bytes - the complete file.
 * @param extension - the suffix, without its dot, used as the fallback.
 * @returns the identified format, or undefined when nothing identifies it.
 */
export function sniffImageFormat(bytes: Uint8Array, extension: string): ImageFormat | undefined {
  const fallback = formatByKey(EXTENSION_FORMATS[extension.toLowerCase()])
  if (bytes.byteLength >= 8) {
    // Gzip comes first: an SVGZ is a gzip stream, and its payload is only
    // readable after inflating, which the body does asynchronously.
    if (bytes[0] === 0x1f && bytes[1] === 0x8b) return pick(COMPRESSED, 'svgz')
    if (bytes[0] === 0x89 && matchesAscii(bytes, 1, 'PNG')) return pick(NATIVE, 'png')
    if (bytes[0] === 0xff && bytes[1] === 0xd8 && bytes[2] === 0xff) return pick(NATIVE, 'jpeg')
    if (matchesAscii(bytes, 0, 'GIF87a') || matchesAscii(bytes, 0, 'GIF89a')) return pick(NATIVE, 'gif')
    if (matchesAscii(bytes, 0, 'RIFF') && matchesAscii(bytes, 8, 'WEBP')) return pick(NATIVE, 'webp')
    if (matchesAscii(bytes, 0, 'BM')) return pick(NATIVE, 'bmp')
    if (matchesAscii(bytes, 4, 'ftyp')) {
      const brand = String.fromCharCode(...bytes.slice(8, 12))
      const key = ISO_BRANDS[brand]
      if (key !== undefined) return formatByKey(key)
    }
    if (matchesAscii(bytes, 4, 'jP  ') || (bytes[0] === 0xff && bytes[1] === 0x4f)) return pick(UNSUPPORTED, 'jp2')
    if (bytes[0] === 0xff && bytes[1] === 0x0a) return pick(UNSUPPORTED, 'jxl')
    if (matchesAscii(bytes, 0, '8BPS')) return pick(UNSUPPORTED, 'psd')
    if (matchesAscii(bytes, 0, 'DDS ')) return pick(UNSUPPORTED, 'dds')
    if (bytes[0] === 0x76 && bytes[1] === 0x2f && bytes[2] === 0x31 && bytes[3] === 0x01) return pick(UNSUPPORTED, 'exr')
    if (matchesAscii(bytes, 0, '#?RADIANCE') || matchesAscii(bytes, 0, '#?RGBE')) return pick(UNSUPPORTED, 'hdr')
    // `qoif` is QOI's own marker. It is not a JPEG XL marker, so it must not be
    // reported as one: a reader told the wrong format converts the wrong way.
    if (matchesAscii(bytes, 0, 'qoif')) return pick(UNSUPPORTED, 'qoi')
    if (bytes[0] === 0x00 && bytes[1] === 0x00 && (bytes[2] === 0x01 || bytes[2] === 0x02) && bytes[3] === 0x00) return pick(NATIVE, 'ico')
    // An Apple icon set is not an ICO: it has its own container and no reader
    // here, so it is reported by name rather than mislabelled and failed.
    if (matchesAscii(bytes, 0, 'icns')) return pick(UNSUPPORTED, 'icns')
    if (bytes[0] === 0x50 && bytes[1] >= 0x31 && bytes[1] <= 0x36) return pick(UNSUPPORTED, 'pnm')
    if (matchesAscii(bytes, 0, '%!PS')) return pick(UNSUPPORTED, 'eps')
    if (bytes[0] === 0x49 && bytes[1] === 0x49 && bytes[2] === 0x2a && bytes[3] === 0x00) {
      // `II*\0` is TIFF's little-endian signature, and several RAW formats are
      // TIFF containers that brand themselves at offset 8.
      const brand = bytes.byteLength >= 12 ? String.fromCharCode(...bytes.slice(8, 12)).trim() : ''
      for (const [marker, key] of Object.entries(TIFF_BASED_RAW)) {
        if (brand.startsWith(marker)) return formatByKey(key)
      }
      return pick(DECODED, 'tiff')
    }
    if (bytes[0] === 0x4d && bytes[1] === 0x4d && bytes[2] === 0x00 && bytes[3] === 0x2a) return pick(DECODED, 'tiff')
  }
  // SVG is text, so its signature is searched rather than matched at a fixed
  // offset: an XML declaration or a comment may precede the root element.
  if (bytes.byteLength >= 4) {
    const head = new TextDecoder('utf-8', { fatal: false })
      .decode(bytes.subarray(0, Math.min(bytes.byteLength, 1024)))
    if (/<svg[\s>]/i.test(head)) return pick(NATIVE, 'svg')
    // XPM and XBM are C source, and neither is Netpbm, so the signature decides
    // the name the reader is given.
    if (/^\s*\/\* XPM \*\//.test(head) || /^\s*#define\s+\w+_width/.test(head)) return pick(UNSUPPORTED, 'xpm')
  }
  return fallback
}
