/**
 * Generated official-vendor and model presets for the SDKWork video model
 * configuration page: the catalog's own video generation vendors with their canonical
 * API roots, and every catalog model in that modality.
 *
 * Source: sdkwork-models catalog 2026.09.17.1 (generatedAt 2026-09-17T00:00:00Z).
 * Regenerate with `node scripts/generate-sdkwork-model-presets.mjs`; do not edit by hand.
 */

/** One official vendor root the video settings page can seed. */
export interface SdkworkVideoVendorPreset {
  /** sdkwork-models vendor code. */
  readonly vendor: string
  /** Vendor name as the catalog spells it. */
  readonly displayName: string
  /** Catalog region this root belongs to (`global`, `cn`). */
  readonly region: string
  /** Preferred protocol code; empty when the catalog publishes no compatible root. */
  readonly protocol: string
  /** Canonical API root; empty when the catalog publishes no compatible root. */
  readonly baseUrl: string
  /** Every protocol code the vendor publishes a root for. */
  readonly protocols: readonly string[]
}

/** One catalog model the video settings page can offer. */
export interface SdkworkVideoModelPreset {
  /** Catalog key (`<vendor>/<modelId>`). */
  readonly catalogKey: string
  /** Wire model id the provider expects. */
  readonly modelId: string
  /** Vendor name as the catalog spells it. */
  readonly displayName: string
  /** Owning sdkwork-models vendor code. */
  readonly vendor: string
  /** Catalog region this model belongs to. */
  readonly region: string
  /** Vendor API shape the catalog records for the model. */
  readonly apiFormat: string
  /** Catalog lifecycle stage. */
  readonly lifecycle: string
}

/** Official vendor roots with a video capability. */
export const OFFICIAL_VIDEO_VENDOR_PRESETS: readonly SdkworkVideoVendorPreset[] = [
  {
    vendor: 'alibaba',
    displayName: 'Alibaba Cloud',
    region: 'cn',
    protocol: 'openai_compatible',
    baseUrl: 'https://dashscope.aliyuncs.com/compatible-mode/v1',
    protocols: ['anthropic_messages', 'openai_compatible', 'openai_responses'],
  },
  {
    vendor: 'black_forest_labs',
    displayName: 'Black Forest Labs',
    region: 'global',
    protocol: '',
    baseUrl: '',
    protocols: [],
  },
  {
    vendor: 'bytedance',
    displayName: 'ByteDance',
    region: 'cn',
    protocol: 'openai_compatible',
    baseUrl: 'https://ark.cn-beijing.volces.com/api/v3',
    protocols: ['openai_compatible', 'openai_responses'],
  },
  {
    vendor: 'bytedance',
    displayName: 'ByteDance',
    region: 'global',
    protocol: 'openai_compatible',
    baseUrl: 'https://ark.cn-beijing.volces.com/api/v3',
    protocols: ['openai_compatible', 'openai_responses'],
  },
  {
    vendor: 'google',
    displayName: 'Google',
    region: 'global',
    protocol: 'openai_compatible',
    baseUrl: 'https://generativelanguage.googleapis.com/v1beta/openai',
    protocols: ['openai_compatible'],
  },
  {
    vendor: 'kuaishou',
    displayName: 'Kuaishou',
    region: 'cn',
    protocol: '',
    baseUrl: '',
    protocols: [],
  },
  {
    vendor: 'kuaishou',
    displayName: 'Kuaishou',
    region: 'global',
    protocol: '',
    baseUrl: '',
    protocols: [],
  },
  {
    vendor: 'luma_ai',
    displayName: 'Luma AI',
    region: 'global',
    protocol: '',
    baseUrl: '',
    protocols: [],
  },
  {
    vendor: 'minimax',
    displayName: 'MiniMax',
    region: 'cn',
    protocol: 'openai_compatible',
    baseUrl: 'https://api.minimaxi.com/v1',
    protocols: ['openai_compatible'],
  },
  {
    vendor: 'minimax',
    displayName: 'MiniMax',
    region: 'global',
    protocol: 'openai_compatible',
    baseUrl: 'https://api.minimaxi.com/v1',
    protocols: ['openai_compatible'],
  },
  {
    vendor: 'openai',
    displayName: 'OpenAI',
    region: 'global',
    protocol: 'openai_compatible',
    baseUrl: 'https://api.openai.com/v1',
    protocols: ['openai_compatible', 'openai_responses'],
  },
  {
    vendor: 'pixverse',
    displayName: 'PixVerse',
    region: 'cn',
    protocol: '',
    baseUrl: '',
    protocols: [],
  },
  {
    vendor: 'pixverse',
    displayName: 'PixVerse',
    region: 'global',
    protocol: '',
    baseUrl: '',
    protocols: [],
  },
  {
    vendor: 'runway',
    displayName: 'Runway',
    region: 'global',
    protocol: '',
    baseUrl: '',
    protocols: [],
  },
  {
    vendor: 'vidu',
    displayName: 'Vidu',
    region: 'cn',
    protocol: '',
    baseUrl: '',
    protocols: [],
  },
  {
    vendor: 'vidu',
    displayName: 'Vidu',
    region: 'global',
    protocol: '',
    baseUrl: '',
    protocols: [],
  },
  {
    vendor: 'xai',
    displayName: 'xAI',
    region: 'global',
    protocol: 'openai_compatible',
    baseUrl: 'https://api.x.ai/v1',
    protocols: ['openai_compatible', 'openai_responses'],
  },
  {
    vendor: 'zhipu',
    displayName: 'Zhipu AI',
    region: 'cn',
    protocol: 'openai_compatible',
    baseUrl: 'https://open.bigmodel.cn/api/paas/v4',
    protocols: ['anthropic_messages', 'openai_compatible'],
  },
]

/** Every catalog model whose primary capability is video. */
export const CATALOG_VIDEO_MODEL_PRESETS: readonly SdkworkVideoModelPreset[] = [
  {
    catalogKey: 'alibaba/wan2.6-i2v',
    modelId: 'wan2.6-i2v',
    displayName: 'Wan 2.6 Image to Video',
    vendor: 'alibaba',
    region: 'cn',
    apiFormat: 'vendor_native',
    lifecycle: 'active',
  },
  {
    catalogKey: 'alibaba/wan2.6-r2v',
    modelId: 'wan2.6-r2v',
    displayName: 'Wan 2.6 Reference to Video',
    vendor: 'alibaba',
    region: 'cn',
    apiFormat: 'vendor_native',
    lifecycle: 'active',
  },
  {
    catalogKey: 'alibaba/wan2.6-t2v',
    modelId: 'wan2.6-t2v',
    displayName: 'Wan 2.6 Text to Video',
    vendor: 'alibaba',
    region: 'cn',
    apiFormat: 'vendor_native',
    lifecycle: 'active',
  },
  {
    catalogKey: 'black_forest_labs/flux-3',
    modelId: 'flux-3',
    displayName: 'FLUX.3',
    vendor: 'black_forest_labs',
    region: 'global',
    apiFormat: 'vendor_native',
    lifecycle: 'active',
  },
  {
    catalogKey: 'bytedance/doubao-seedance-2-0-260128',
    modelId: 'doubao-seedance-2-0-260128',
    displayName: 'Doubao Seedance 2.0',
    vendor: 'bytedance',
    region: 'cn',
    apiFormat: 'vendor_native',
    lifecycle: 'active',
  },
  {
    catalogKey: 'bytedance/doubao-seedance-2-0-260128',
    modelId: 'doubao-seedance-2-0-260128',
    displayName: 'Doubao Seedance 2.0',
    vendor: 'bytedance',
    region: 'global',
    apiFormat: 'vendor_native',
    lifecycle: 'deprecated',
  },
  {
    catalogKey: 'bytedance/doubao-seedance-2-0-fast-260128',
    modelId: 'doubao-seedance-2-0-fast-260128',
    displayName: 'Doubao Seedance 2.0 Fast',
    vendor: 'bytedance',
    region: 'cn',
    apiFormat: 'vendor_native',
    lifecycle: 'active',
  },
  {
    catalogKey: 'bytedance/doubao-seedance-2-0-fast-260128',
    modelId: 'doubao-seedance-2-0-fast-260128',
    displayName: 'Doubao Seedance 2.0 Fast',
    vendor: 'bytedance',
    region: 'global',
    apiFormat: 'vendor_native',
    lifecycle: 'deprecated',
  },
  {
    catalogKey: 'bytedance/doubao-seedance-2-0-mini-260615',
    modelId: 'doubao-seedance-2-0-mini-260615',
    displayName: 'Doubao Seedance 2.0 Mini',
    vendor: 'bytedance',
    region: 'cn',
    apiFormat: 'vendor_native',
    lifecycle: 'active',
  },
  {
    catalogKey: 'bytedance/doubao-seedance-2-5-260623',
    modelId: 'doubao-seedance-2-5-260623',
    displayName: 'Doubao Seedance 2.5',
    vendor: 'bytedance',
    region: 'cn',
    apiFormat: 'vendor_native',
    lifecycle: 'deprecated',
  },
  {
    catalogKey: 'bytedance/doubao-seedance-2-5-260628',
    modelId: 'doubao-seedance-2-5-260628',
    displayName: 'Doubao Seedance 2.5 (260628)',
    vendor: 'bytedance',
    region: 'cn',
    apiFormat: 'vendor_native',
    lifecycle: 'active',
  },
  {
    catalogKey: 'bytedance/dreamina-seedance-2-0-260128',
    modelId: 'dreamina-seedance-2-0-260128',
    displayName: 'Dreamina Seedance 2.0',
    vendor: 'bytedance',
    region: 'global',
    apiFormat: 'vendor_native',
    lifecycle: 'active',
  },
  {
    catalogKey: 'bytedance/dreamina-seedance-2-0-fast-260128',
    modelId: 'dreamina-seedance-2-0-fast-260128',
    displayName: 'Dreamina Seedance 2.0 Fast',
    vendor: 'bytedance',
    region: 'global',
    apiFormat: 'vendor_native',
    lifecycle: 'active',
  },
  {
    catalogKey: 'bytedance/dreamina-seedance-2-0-mini-260615',
    modelId: 'dreamina-seedance-2-0-mini-260615',
    displayName: 'Dreamina Seedance 2.0 Mini',
    vendor: 'bytedance',
    region: 'global',
    apiFormat: 'vendor_native',
    lifecycle: 'active',
  },
  {
    catalogKey: 'bytedance/dreamina-seedance-2-5-260628',
    modelId: 'dreamina-seedance-2-5-260628',
    displayName: 'Dreamina Seedance 2.5',
    vendor: 'bytedance',
    region: 'global',
    apiFormat: 'vendor_native',
    lifecycle: 'active',
  },
  {
    catalogKey: 'google/gemini-omni-1.1-flash',
    modelId: 'gemini-omni-1.1-flash',
    displayName: 'Gemini Omni 1.1 Flash',
    vendor: 'google',
    region: 'global',
    apiFormat: 'google_gemini',
    lifecycle: 'active',
  },
  {
    catalogKey: 'google/gemini-omni-flash-preview',
    modelId: 'gemini-omni-flash-preview',
    displayName: 'Gemini Omni Flash Preview',
    vendor: 'google',
    region: 'global',
    apiFormat: 'google_gemini',
    lifecycle: 'preview',
  },
  {
    catalogKey: 'google/veo-3.1-fast-generate-preview',
    modelId: 'veo-3.1-fast-generate-preview',
    displayName: 'Veo 3.1 Fast Generate Preview',
    vendor: 'google',
    region: 'global',
    apiFormat: 'vendor_native',
    lifecycle: 'preview',
  },
  {
    catalogKey: 'google/veo-3.1-generate-preview',
    modelId: 'veo-3.1-generate-preview',
    displayName: 'Veo 3.1 Generate Preview',
    vendor: 'google',
    region: 'global',
    apiFormat: 'vendor_native',
    lifecycle: 'preview',
  },
  {
    catalogKey: 'google/veo-3.1-lite-generate-preview',
    modelId: 'veo-3.1-lite-generate-preview',
    displayName: 'Veo 3.1 Lite Generate Preview',
    vendor: 'google',
    region: 'global',
    apiFormat: 'vendor_native',
    lifecycle: 'preview',
  },
  {
    catalogKey: 'kuaishou/kling-3.0-turbo',
    modelId: 'kling-3.0-turbo',
    displayName: 'Kling 3.0 Turbo',
    vendor: 'kuaishou',
    region: 'cn',
    apiFormat: 'vendor_native',
    lifecycle: 'active',
  },
  {
    catalogKey: 'kuaishou/kling-3.0-turbo',
    modelId: 'kling-3.0-turbo',
    displayName: 'Kling 3.0 Turbo',
    vendor: 'kuaishou',
    region: 'global',
    apiFormat: 'vendor_native',
    lifecycle: 'active',
  },
  {
    catalogKey: 'kuaishou/kling-ai-avatar-v2',
    modelId: 'kling-ai-avatar-v2',
    displayName: 'Kling Avatar',
    vendor: 'kuaishou',
    region: 'cn',
    apiFormat: 'vendor_native',
    lifecycle: 'active',
  },
  {
    catalogKey: 'kuaishou/kling-ai-avatar-v2',
    modelId: 'kling-ai-avatar-v2',
    displayName: 'Kling Avatar',
    vendor: 'kuaishou',
    region: 'global',
    apiFormat: 'vendor_native',
    lifecycle: 'active',
  },
  {
    catalogKey: 'kuaishou/kling-v2-5-turbo',
    modelId: 'kling-v2-5-turbo',
    displayName: 'Kling 2.5 Turbo',
    vendor: 'kuaishou',
    region: 'cn',
    apiFormat: 'vendor_native',
    lifecycle: 'active',
  },
  {
    catalogKey: 'kuaishou/kling-v2-5-turbo',
    modelId: 'kling-v2-5-turbo',
    displayName: 'Kling 2.5 Turbo',
    vendor: 'kuaishou',
    region: 'global',
    apiFormat: 'vendor_native',
    lifecycle: 'active',
  },
  {
    catalogKey: 'kuaishou/kling-v2-6',
    modelId: 'kling-v2-6',
    displayName: 'Kling 2.6',
    vendor: 'kuaishou',
    region: 'cn',
    apiFormat: 'vendor_native',
    lifecycle: 'active',
  },
  {
    catalogKey: 'kuaishou/kling-v2-6',
    modelId: 'kling-v2-6',
    displayName: 'Kling 2.6',
    vendor: 'kuaishou',
    region: 'global',
    apiFormat: 'vendor_native',
    lifecycle: 'active',
  },
  {
    catalogKey: 'kuaishou/kling-v3',
    modelId: 'kling-v3',
    displayName: 'Kling v3',
    vendor: 'kuaishou',
    region: 'cn',
    apiFormat: 'vendor_native',
    lifecycle: 'active',
  },
  {
    catalogKey: 'kuaishou/kling-v3',
    modelId: 'kling-v3',
    displayName: 'Kling v3',
    vendor: 'kuaishou',
    region: 'global',
    apiFormat: 'vendor_native',
    lifecycle: 'active',
  },
  {
    catalogKey: 'kuaishou/kling-v3-0-preview',
    modelId: 'kling-v3-0-preview',
    displayName: 'Kling v3.0 Preview',
    vendor: 'kuaishou',
    region: 'cn',
    apiFormat: 'vendor_native',
    lifecycle: 'deprecated',
  },
  {
    catalogKey: 'kuaishou/kling-v3-0-preview',
    modelId: 'kling-v3-0-preview',
    displayName: 'Kling v3.0 Preview',
    vendor: 'kuaishou',
    region: 'global',
    apiFormat: 'vendor_native',
    lifecycle: 'deprecated',
  },
  {
    catalogKey: 'kuaishou/kling-v3-omni',
    modelId: 'kling-v3-omni',
    displayName: 'Kling v3 Omni',
    vendor: 'kuaishou',
    region: 'cn',
    apiFormat: 'vendor_native',
    lifecycle: 'active',
  },
  {
    catalogKey: 'kuaishou/kling-v3-omni',
    modelId: 'kling-v3-omni',
    displayName: 'Kling v3 Omni',
    vendor: 'kuaishou',
    region: 'global',
    apiFormat: 'vendor_native',
    lifecycle: 'active',
  },
  {
    catalogKey: 'kuaishou/kling-video-o1',
    modelId: 'kling-video-o1',
    displayName: 'Kling O1',
    vendor: 'kuaishou',
    region: 'cn',
    apiFormat: 'vendor_native',
    lifecycle: 'active',
  },
  {
    catalogKey: 'kuaishou/kling-video-o1',
    modelId: 'kling-video-o1',
    displayName: 'Kling O1',
    vendor: 'kuaishou',
    region: 'global',
    apiFormat: 'vendor_native',
    lifecycle: 'active',
  },
  {
    catalogKey: 'luma_ai/ray-2',
    modelId: 'ray-2',
    displayName: 'Ray 2',
    vendor: 'luma_ai',
    region: 'global',
    apiFormat: 'vendor_native',
    lifecycle: 'deprecated',
  },
  {
    catalogKey: 'luma_ai/ray-3',
    modelId: 'ray-3',
    displayName: 'Ray 3',
    vendor: 'luma_ai',
    region: 'global',
    apiFormat: 'vendor_native',
    lifecycle: 'deprecated',
  },
  {
    catalogKey: 'luma_ai/ray-3.14',
    modelId: 'ray-3.14',
    displayName: 'Ray 3.14 (Pi)',
    vendor: 'luma_ai',
    region: 'global',
    apiFormat: 'vendor_native',
    lifecycle: 'deprecated',
  },
  {
    catalogKey: 'luma_ai/ray-3.2',
    modelId: 'ray-3.2',
    displayName: 'Ray 3.2',
    vendor: 'luma_ai',
    region: 'global',
    apiFormat: 'vendor_native',
    lifecycle: 'active',
  },
  {
    catalogKey: 'luma_ai/ray-flash-2',
    modelId: 'ray-flash-2',
    displayName: 'Ray 2 Flash',
    vendor: 'luma_ai',
    region: 'global',
    apiFormat: 'vendor_native',
    lifecycle: 'deprecated',
  },
  {
    catalogKey: 'minimax/hailuo-02',
    modelId: 'hailuo-02',
    displayName: 'Hailuo 02',
    vendor: 'minimax',
    region: 'cn',
    apiFormat: 'vendor_native',
    lifecycle: 'active',
  },
  {
    catalogKey: 'minimax/hailuo-02',
    modelId: 'hailuo-02',
    displayName: 'Hailuo 02',
    vendor: 'minimax',
    region: 'global',
    apiFormat: 'vendor_native',
    lifecycle: 'active',
  },
  {
    catalogKey: 'minimax/hailuo-2.3',
    modelId: 'hailuo-2.3',
    displayName: 'Hailuo 2.3',
    vendor: 'minimax',
    region: 'cn',
    apiFormat: 'vendor_native',
    lifecycle: 'active',
  },
  {
    catalogKey: 'minimax/hailuo-2.3',
    modelId: 'hailuo-2.3',
    displayName: 'Hailuo 2.3',
    vendor: 'minimax',
    region: 'global',
    apiFormat: 'vendor_native',
    lifecycle: 'active',
  },
  {
    catalogKey: 'minimax/hailuo-2.3-fast',
    modelId: 'hailuo-2.3-fast',
    displayName: 'Hailuo 2.3 Fast',
    vendor: 'minimax',
    region: 'cn',
    apiFormat: 'vendor_native',
    lifecycle: 'active',
  },
  {
    catalogKey: 'minimax/hailuo-2.3-fast',
    modelId: 'hailuo-2.3-fast',
    displayName: 'Hailuo 2.3 Fast',
    vendor: 'minimax',
    region: 'global',
    apiFormat: 'vendor_native',
    lifecycle: 'active',
  },
  {
    catalogKey: 'minimax/MiniMax-H3',
    modelId: 'MiniMax-H3',
    displayName: 'MiniMax H3',
    vendor: 'minimax',
    region: 'cn',
    apiFormat: 'vendor_native',
    lifecycle: 'active',
  },
  {
    catalogKey: 'minimax/MiniMax-H3',
    modelId: 'MiniMax-H3',
    displayName: 'MiniMax H3',
    vendor: 'minimax',
    region: 'global',
    apiFormat: 'vendor_native',
    lifecycle: 'active',
  },
  {
    catalogKey: 'minimax/MiniMax-H3-Max',
    modelId: 'MiniMax-H3-Max',
    displayName: 'MiniMax H3 Max',
    vendor: 'minimax',
    region: 'cn',
    apiFormat: 'vendor_native',
    lifecycle: 'active',
  },
  {
    catalogKey: 'minimax/MiniMax-H3-Max',
    modelId: 'MiniMax-H3-Max',
    displayName: 'MiniMax H3 Max',
    vendor: 'minimax',
    region: 'global',
    apiFormat: 'vendor_native',
    lifecycle: 'active',
  },
  {
    catalogKey: 'minimax/MiniMax-H3-Regeneration',
    modelId: 'MiniMax-H3-Regeneration',
    displayName: 'MiniMax H3 Regeneration',
    vendor: 'minimax',
    region: 'cn',
    apiFormat: 'vendor_native',
    lifecycle: 'active',
  },
  {
    catalogKey: 'minimax/MiniMax-H3-Regeneration',
    modelId: 'MiniMax-H3-Regeneration',
    displayName: 'MiniMax H3 Regeneration',
    vendor: 'minimax',
    region: 'global',
    apiFormat: 'vendor_native',
    lifecycle: 'active',
  },
  {
    catalogKey: 'openai/sora-2',
    modelId: 'sora-2',
    displayName: 'Sora 2',
    vendor: 'openai',
    region: 'global',
    apiFormat: 'openai_compatible',
    lifecycle: 'deprecated',
  },
  {
    catalogKey: 'openai/sora-2-pro',
    modelId: 'sora-2-pro',
    displayName: 'Sora 2 Pro',
    vendor: 'openai',
    region: 'global',
    apiFormat: 'openai_compatible',
    lifecycle: 'deprecated',
  },
  {
    catalogKey: 'pixverse/pixverse-c1',
    modelId: 'pixverse-c1',
    displayName: 'PixVerse C1',
    vendor: 'pixverse',
    region: 'global',
    apiFormat: 'vendor_native',
    lifecycle: 'preview',
  },
  {
    catalogKey: 'pixverse/pixverse-c1-t2v',
    modelId: 'pixverse-c1-t2v',
    displayName: 'PixVerse C1 Text to Video',
    vendor: 'pixverse',
    region: 'cn',
    apiFormat: 'vendor_native',
    lifecycle: 'active',
  },
  {
    catalogKey: 'pixverse/pixverse-v5.6-t2v',
    modelId: 'pixverse-v5.6-t2v',
    displayName: 'PixVerse V5.6 Text to Video',
    vendor: 'pixverse',
    region: 'cn',
    apiFormat: 'vendor_native',
    lifecycle: 'preview',
  },
  {
    catalogKey: 'pixverse/pixverse-v6',
    modelId: 'pixverse-v6',
    displayName: 'PixVerse V6',
    vendor: 'pixverse',
    region: 'global',
    apiFormat: 'vendor_native',
    lifecycle: 'active',
  },
  {
    catalogKey: 'pixverse/pixverse-v6-t2v',
    modelId: 'pixverse-v6-t2v',
    displayName: 'PixVerse V6 Text to Video',
    vendor: 'pixverse',
    region: 'cn',
    apiFormat: 'vendor_native',
    lifecycle: 'active',
  },
  {
    catalogKey: 'runway/act_two',
    modelId: 'act_two',
    displayName: 'Act-Two',
    vendor: 'runway',
    region: 'global',
    apiFormat: 'vendor_native',
    lifecycle: 'active',
  },
  {
    catalogKey: 'runway/aleph2',
    modelId: 'aleph2',
    displayName: 'Aleph 2.0',
    vendor: 'runway',
    region: 'global',
    apiFormat: 'vendor_native',
    lifecycle: 'active',
  },
  {
    catalogKey: 'runway/gemini_omni_flash',
    modelId: 'gemini_omni_flash',
    displayName: 'Gemini Omni Flash',
    vendor: 'runway',
    region: 'global',
    apiFormat: 'vendor_native',
    lifecycle: 'active',
  },
  {
    catalogKey: 'runway/gen4_turbo',
    modelId: 'gen4_turbo',
    displayName: 'Gen-4 Turbo',
    vendor: 'runway',
    region: 'global',
    apiFormat: 'vendor_native',
    lifecycle: 'active',
  },
  {
    catalogKey: 'runway/gen4.5',
    modelId: 'gen4.5',
    displayName: 'Gen-4.5',
    vendor: 'runway',
    region: 'global',
    apiFormat: 'vendor_native',
    lifecycle: 'active',
  },
  {
    catalogKey: 'runway/grok_imagine_1_5',
    modelId: 'grok_imagine_1_5',
    displayName: 'Grok Imagine Video 1.5',
    vendor: 'runway',
    region: 'global',
    apiFormat: 'vendor_native',
    lifecycle: 'active',
  },
  {
    catalogKey: 'runway/gwm1_avatars',
    modelId: 'gwm1_avatars',
    displayName: 'GWM1 Avatars',
    vendor: 'runway',
    region: 'global',
    apiFormat: 'vendor_native',
    lifecycle: 'active',
  },
  {
    catalogKey: 'runway/h3_max',
    modelId: 'h3_max',
    displayName: 'MiniMax H3 Max',
    vendor: 'runway',
    region: 'global',
    apiFormat: 'vendor_native',
    lifecycle: 'active',
  },
  {
    catalogKey: 'runway/hailuo3',
    modelId: 'hailuo3',
    displayName: 'MiniMax Hailuo 3',
    vendor: 'runway',
    region: 'global',
    apiFormat: 'vendor_native',
    lifecycle: 'active',
  },
  {
    catalogKey: 'runway/happyhorse_1_0',
    modelId: 'happyhorse_1_0',
    displayName: 'HappyHorse 1.0',
    vendor: 'runway',
    region: 'global',
    apiFormat: 'vendor_native',
    lifecycle: 'active',
  },
  {
    catalogKey: 'runway/magnific_video_upscaler_creative',
    modelId: 'magnific_video_upscaler_creative',
    displayName: 'Magnific Video Upscaler Creative',
    vendor: 'runway',
    region: 'global',
    apiFormat: 'vendor_native',
    lifecycle: 'preview',
  },
  {
    catalogKey: 'runway/ruby',
    modelId: 'ruby',
    displayName: 'Ruby (SDR to HDR)',
    vendor: 'runway',
    region: 'global',
    apiFormat: 'vendor_native',
    lifecycle: 'active',
  },
  {
    catalogKey: 'runway/seedance2',
    modelId: 'seedance2',
    displayName: 'Seedance 2.0',
    vendor: 'runway',
    region: 'global',
    apiFormat: 'vendor_native',
    lifecycle: 'active',
  },
  {
    catalogKey: 'runway/seedance2_5',
    modelId: 'seedance2_5',
    displayName: 'Seedance 2.5',
    vendor: 'runway',
    region: 'global',
    apiFormat: 'vendor_native',
    lifecycle: 'active',
  },
  {
    catalogKey: 'runway/seedance2_fast',
    modelId: 'seedance2_fast',
    displayName: 'Seedance 2.0 Fast',
    vendor: 'runway',
    region: 'global',
    apiFormat: 'vendor_native',
    lifecycle: 'active',
  },
  {
    catalogKey: 'runway/seedance2_mini',
    modelId: 'seedance2_mini',
    displayName: 'Seedance 2.0 Mini',
    vendor: 'runway',
    region: 'global',
    apiFormat: 'vendor_native',
    lifecycle: 'active',
  },
  {
    catalogKey: 'runway/veo3.1',
    modelId: 'veo3.1',
    displayName: 'Veo 3.1',
    vendor: 'runway',
    region: 'global',
    apiFormat: 'vendor_native',
    lifecycle: 'active',
  },
  {
    catalogKey: 'runway/veo3.1_fast',
    modelId: 'veo3.1_fast',
    displayName: 'Veo 3.1 Fast',
    vendor: 'runway',
    region: 'global',
    apiFormat: 'vendor_native',
    lifecycle: 'active',
  },
  {
    catalogKey: 'runway/wan3',
    modelId: 'wan3',
    displayName: 'WAN 3',
    vendor: 'runway',
    region: 'global',
    apiFormat: 'vendor_native',
    lifecycle: 'active',
  },
  {
    catalogKey: 'vidu/viduq3',
    modelId: 'viduq3',
    displayName: 'Vidu Q3',
    vendor: 'vidu',
    region: 'cn',
    apiFormat: 'vendor_native',
    lifecycle: 'active',
  },
  {
    catalogKey: 'vidu/viduq3',
    modelId: 'viduq3',
    displayName: 'Vidu Q3',
    vendor: 'vidu',
    region: 'global',
    apiFormat: 'vendor_native',
    lifecycle: 'active',
  },
  {
    catalogKey: 'vidu/viduq3-ad',
    modelId: 'viduq3-ad',
    displayName: 'Vidu Q3 Ad',
    vendor: 'vidu',
    region: 'cn',
    apiFormat: 'vendor_native',
    lifecycle: 'preview',
  },
  {
    catalogKey: 'vidu/viduq3-ad',
    modelId: 'viduq3-ad',
    displayName: 'Vidu Q3 Ad',
    vendor: 'vidu',
    region: 'global',
    apiFormat: 'vendor_native',
    lifecycle: 'preview',
  },
  {
    catalogKey: 'vidu/viduq3-drama',
    modelId: 'viduq3-drama',
    displayName: 'Vidu Q3 Drama',
    vendor: 'vidu',
    region: 'cn',
    apiFormat: 'vendor_native',
    lifecycle: 'preview',
  },
  {
    catalogKey: 'vidu/viduq3-drama',
    modelId: 'viduq3-drama',
    displayName: 'Vidu Q3 Drama',
    vendor: 'vidu',
    region: 'global',
    apiFormat: 'vendor_native',
    lifecycle: 'preview',
  },
  {
    catalogKey: 'vidu/viduq3-mix',
    modelId: 'viduq3-mix',
    displayName: 'Vidu Q3 Mix',
    vendor: 'vidu',
    region: 'cn',
    apiFormat: 'vendor_native',
    lifecycle: 'active',
  },
  {
    catalogKey: 'vidu/viduq3-mix',
    modelId: 'viduq3-mix',
    displayName: 'Vidu Q3 Mix',
    vendor: 'vidu',
    region: 'global',
    apiFormat: 'vendor_native',
    lifecycle: 'active',
  },
  {
    catalogKey: 'vidu/viduq3-pro',
    modelId: 'viduq3-pro',
    displayName: 'Vidu Q3 Pro',
    vendor: 'vidu',
    region: 'cn',
    apiFormat: 'vendor_native',
    lifecycle: 'active',
  },
  {
    catalogKey: 'vidu/viduq3-pro',
    modelId: 'viduq3-pro',
    displayName: 'Vidu Q3 Pro',
    vendor: 'vidu',
    region: 'global',
    apiFormat: 'vendor_native',
    lifecycle: 'active',
  },
  {
    catalogKey: 'vidu/viduq3-pro-fast',
    modelId: 'viduq3-pro-fast',
    displayName: 'Vidu Q3 Pro Fast',
    vendor: 'vidu',
    region: 'cn',
    apiFormat: 'vendor_native',
    lifecycle: 'active',
  },
  {
    catalogKey: 'vidu/viduq3-pro-fast',
    modelId: 'viduq3-pro-fast',
    displayName: 'Vidu Q3 Pro Fast',
    vendor: 'vidu',
    region: 'global',
    apiFormat: 'vendor_native',
    lifecycle: 'active',
  },
  {
    catalogKey: 'vidu/viduq3-turbo',
    modelId: 'viduq3-turbo',
    displayName: 'Vidu Q3 Turbo',
    vendor: 'vidu',
    region: 'cn',
    apiFormat: 'vendor_native',
    lifecycle: 'active',
  },
  {
    catalogKey: 'vidu/viduq3-turbo',
    modelId: 'viduq3-turbo',
    displayName: 'Vidu Q3 Turbo',
    vendor: 'vidu',
    region: 'global',
    apiFormat: 'vendor_native',
    lifecycle: 'active',
  },
  {
    catalogKey: 'xai/grok-imagine-video',
    modelId: 'grok-imagine-video',
    displayName: 'Grok Imagine Video',
    vendor: 'xai',
    region: 'global',
    apiFormat: 'openai_compatible',
    lifecycle: 'active',
  },
  {
    catalogKey: 'xai/grok-imagine-video-1.5',
    modelId: 'grok-imagine-video-1.5',
    displayName: 'Grok Imagine Video 1.5',
    vendor: 'xai',
    region: 'global',
    apiFormat: 'openai_compatible',
    lifecycle: 'active',
  },
  {
    catalogKey: 'zhipu/cogvideox-3',
    modelId: 'cogvideox-3',
    displayName: 'CogVideoX-3',
    vendor: 'zhipu',
    region: 'cn',
    apiFormat: 'vendor_native',
    lifecycle: 'active',
  },
]
