[package]
name = "sdkwork-api-birdcoder2-assembly"
edition.workspace = true
version = "0.1.0"
description = "Generated API assembly for sdkwork-birdcoder2 application HTTP plane."

[lib]
name = "sdkwork_api_birdcoder2_assembly"
path = "src/lib.rs"

[dependencies]
axum.workspace = true
tokio.workspace = true
sdkwork-web-bootstrap.workspace = true
sdkwork-web-core.workspace = true
sdkwork-birdcoder2-host-runtime-service = { workspace = true }
sdkwork-routes-birdcoder2-app-api.workspace = true
sdkwork-routes-birdcoder2-internal-api.workspace = true
