environment = "development"

[http]

[[http.server]]
listen = ["80"]
serverName = ["birdcoder2-dev.sdkwork.com", "birdcoder2-dev.birdcoder.com", "birdcoder2-dev.dtupay.com", "birdcoder2-dev.sdkwork.cn", "birdcoder2-dev.birdcoder.cn", "birdcoder2-dev.dtupay.cn", "birdcoder2-dev.skubc.com", "birdcoder2-dev.skubc.cn", "birdcoder2-dev.zowalk.com", "birdcoder2-dev.zowalk.cn", "birdcoder2-dev.offer86.com", "birdcoder2-dev.offer86.cn", "birdcoder2-dev.86offer.com", "birdcoder2-dev.86offer.cn", "harness-dev.sdkwork.com"]
include = ["snippets/gateway-locations.nonproduction.conf"]
